kind: pipeline
name: docker

trigger:
  branch:
    - main

workspace:
  path: /go/src/github.com/checkpoint-restore/criu

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: build-debian11-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/debian:11
    environment:
      BUILD_VERSION: 3.19
      BUILD_OS: debian11
      BUILD_ARCH: amd64
    commands:
      - bash ./.beagle/build.sh

  - name: build-debian12-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/debian:12
    environment:
      BUILD_VERSION: 3.19
      BUILD_OS: debian12
      BUILD_ARCH: amd64
    commands:
      - bash ./.beagle/build.sh

  - name: minio
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
    environment:
      S3_ACCESS_KEY:
        from_secret: ACCESS_KEY_MINIO
      S3_SECRET_KEY:
        from_secret: SECRET_KEY_MINIO
    commands:
      - mc alias set cache --api=S3v4 https://cache.wodcloud.com $S3_ACCESS_KEY $S3_SECRET_KEY
      - mc cp --recursive build/deb/ cache/vscode/criu

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
